name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@werchethandb"
      - run: npm ci
      - run: npm run build

    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
