# This script gets triggered if there is [Release] in the commit message to master
# Currently [Release] is added as part of version.yml script

name: Publish/ Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@werchethandb"

      - name: cache node modules
        id: cache_node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: build and pubish package
        run: |
          npm run-script build            # builds the angular library
          cd dist/angular-components-lib  # goto dist/{library-name} to create the package
          npm pack                        # create compressed package artifact
          npm publish                     # publish the package

    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
