name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@werchethandb"
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: |
          npm ci                          # This command is similar to npm install, except it's used for continuous integration - uses package-lock.json
          npm run-script build            # builds the angular library
          cd dist/angular-components-lib  # goto dist/{library-name} to create the package
          npm pack                        # create compressed package artifact
          npm publish                     # publish the package

    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
