name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v3
        run: |
          cd projects/angular-components-lib
          npm version patch -m "[RELEASE] %s"
      - run: git push

    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
