name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - run: |
          git config --global user.name 'werchethandb'
          git config --global user.email 'chethan.balakrishna@werner.com'
          cd projects/angular-components-lib
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push "https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}" "${{ github.head_ref }}"
